/**
 * @fileoverview AWS Amplify configuration using amplify_outputs.json.
 * 
 * Simple Amplify configuration that uses the standard amplify_outputs.json
 * file generated by Amplify CLI or CDK. This is the recommended approach.
 */

import { Amplify } from 'aws-amplify';
import amplifyOutputs from '../../amplify_outputs.json';

/**
 * Initialize Amplify with the configuration from amplify_outputs.json.
 * This is the standard Amplify configuration approach.
 */
export const configureAmplify = () => {
  console.log('Configuring Amplify with amplify_outputs.json');
  
  Amplify.configure(amplifyOutputs);
  
  console.log('Amplify configured successfully');
  console.log('GraphQL Endpoint:', amplifyOutputs.api.aws_appsync_graphqlEndpoint);
  console.log('Region:', amplifyOutputs.api.aws_appsync_region);
};

export default amplifyOutputs;